# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-07-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
